# Generated by Django 6.1.2 on 2026-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('unread_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('is_group', models.BooleanField(default=False)),
                ('is_channel', models.BooleanField(default=False)),
            ],
        ),
    ]
