# Generated by Django 6.1.2 on 2026-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
