# Generated by Django 6.1.2 on 2026-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
